name: user_repository
description: Package which manages the authentication and user data.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  firebase_core: ^1.10.0
  google_sign_in: ^5.2.1
  equatable: ^2.0.3
  rxdart: ^0.27.3
  fleasy: ^0.6.0
  deep_pick: ^0.10.0
  kt_dart: ^0.10.0

  shared:
    path: ../shared
